#pragma once

#include "driver/gpio.h"
#include "driver/i2c_master.h"
#include "driver/spi_master.h"

#define BOOT_BUTTON_GPIO GPIO_NUM_0

#define AUDIO_INPUT_SAMPLE_RATE 24000
#define AUDIO_OUTPUT_SAMPLE_RATE 24000

/* VB6824 voice/audio coprocessor UART. */
#define VB6824_TX GPIO_NUM_17
#define VB6824_RX GPIO_NUM_18

#define DISPLAY_WIDTH 360
#define DISPLAY_HEIGHT 360
#define DISPLAY_MIRROR_X true
#define DISPLAY_MIRROR_Y true
#define DISPLAY_SWAP_XY false
#define DISPLAY_OFFSET_X 0
#define DISPLAY_OFFSET_Y 0

#define DISPLAY_BACKLIGHT_OUTPUT_INVERT false

#define QSPI_LCD_HOST SPI3_HOST
#define QSPI_PIN_NUM_LCD_PCLK GPIO_NUM_2
#define QSPI_PIN_NUM_LCD_CS GPIO_NUM_1
#define QSPI_PIN_NUM_LCD_DATA0 GPIO_NUM_6
#define QSPI_PIN_NUM_LCD_DATA1 GPIO_NUM_5
#define QSPI_PIN_NUM_LCD_DATA2 GPIO_NUM_4
#define QSPI_PIN_NUM_LCD_DATA3 GPIO_NUM_3
#define QSPI_PIN_NUM_LCD_RST GPIO_NUM_7
#define QSPI_PIN_NUM_LCD_BL GPIO_NUM_11
#define QSPI_PIN_NUM_LCD_TE GPIO_NUM_14
#define DISPLAY_BACKLIGHT_PIN QSPI_PIN_NUM_LCD_BL

#define TP_SCL GPIO_NUM_8
#define TP_SDA GPIO_NUM_9
#define TP_RST GPIO_NUM_10
#define TP_TE GPIO_NUM_14

#define SD_CLK GPIO_NUM_44
#define SD_D3 GPIO_NUM_43
#define SD_D2 GPIO_NUM_42
#define SD_D1 GPIO_NUM_41
#define SD_D0 GPIO_NUM_40
#define SD_CMD GPIO_NUM_39

#define VBAT_DETECT GPIO_NUM_13
#define CHARGE_DETECT GPIO_NUM_15
